parser_config = {
    'regions': [
        { 'name': 'Москва', 'url': 'moskva', 'key_number': 1 },
        { 'name': 'Санкт-Петербург', 'url': 'sankt-peterburg', 'key_number': 2 },
        { 'name': 'Московская область', 'url': 'moskovskaya-obl', 'key_number': 3 },
        { 'name': 'Ленинградская область', 'url': 'leningradskaya-obl', 'key_number': 4 },
        { 'name': 'Алтайский край', 'url': 'altayskiy-kray', 'key_number': 5 },
        { 'name': 'Амурская область', 'url': 'amurskaya-obl', 'key_number': 6 },
        { 'name': 'Архангельская область', 'url': 'arhangelskaya-obl', 'key_number': 7 },
        { 'name': 'Астраханская область', 'url': 'astrahanskaya-obl', 'key_number': 8 },
        { 'name': 'Белгородская область', 'url': 'belgorodskaya-obl', 'key_number': 9 },
        { 'name': 'Брянская область', 'url': 'bryanskaya-obl', 'key_number': 10 },
        { 'name': 'Владимирская область', 'url': 'vladimirskaya-obl', 'key_number': 11 },
        { 'name': 'Волгоградская область', 'url': 'volgogradskaya-obl', 'key_number': 12 },
        { 'name': 'Воронежская область', 'url': 'voronezhskaya-obl', 'key_number': 13 },
        { 'name': 'Еврейская автономная область', 'url': 'evreyskaya-avtonomnaya-obl', 'key_number': 14 },
        { 'name': 'Забайкальский край', 'url': 'zabaykalskiy-kray', 'key_number': 15 },
        { 'name': 'Свердловская область', 'url': 'sverdlovskaya-obl', 'key_number': 16 },
        { 'name': 'Новосибирская область', 'url': 'novosibirskaya-obl', 'key_number': 17 },
        { 'name': 'Ивановская область', 'url': 'ivanovskaya-obl', 'key_number': 18 },
        { 'name': 'Иркутская область', 'url': 'irkutskaya-obl', 'key_number': 19 },
        { 'name': 'Калининградская область', 'url': 'kaliningradskaya-obl', 'key_number': 20 },
        { 'name': 'Калужская область', 'url': 'kaluzhskaya-obl', 'key_number': 21 },
        { 'name': 'Кемеровская область', 'url': 'kemerovskaya-obl', 'key_number': 22 },
        { 'name': 'Кировская область', 'url': 'kirovskaya-obl', 'key_number': 23 },
        { 'name': 'Краснодарский край', 'url': 'krasnodarskiy-kray', 'key_number': 24 },
        { 'name': 'Красноярский край', 'url': 'krasnoyarskiy-kray', 'key_number': 25 },
        { 'name': 'Курганская область', 'url': 'kurganskaya-obl', 'key_number': 26 },
        { 'name': 'Курская область', 'url': 'kurskaya-obl', 'key_number': 27 },
        { 'name': 'Липетская область', 'url': 'lipetskaya-obl', 'key_number': 28 },
        { 'name': 'Мурманская область', 'url': 'murmanskaya-obl', 'key_number': 29 },
        { 'name': 'Нижнегородская область', 'url': 'nizhegorodskaya-obl', 'key_number': 30 },
        { 'name': 'Новгородская область', 'url': 'novgorodskaya-obl', 'key_number': 31 },
        { 'name': 'Новосибирская область', 'url': 'novosibirskaya-obl', 'key_number': 32 },
        { 'name': 'Омская область', 'url': 'omskaya-obl', 'key_number': 33 },
        { 'name': 'Оренбурская область', 'url': 'orenburgskaya-obl', 'key_number': 34 },
        { 'name': 'Орловская область', 'url': 'orlovskaya-obl', 'key_number': 35 },
        { 'name': 'Пензинская область', 'url': 'penzenskaya-obl', 'key_number': 36 },
        { 'name': 'Пермский край область', 'url': 'permskiy-kray', 'key_number': 37 },
        { 'name': 'Приморский край', 'url': 'primorskiy-kray', 'key_number': 38 },
        { 'name': 'Псковская область', 'url': 'pskovskaya-obl', 'key_number': 39 },
        { 'name': 'Республика адыгея', 'url': 'resp-adyigeya', 'key_number': 40 },
        { 'name': 'Республика алтай', 'url': 'resp-altay', 'key_number': 41 },
        { 'name': 'Республика Башкортостан', 'url': 'resp-bashkortostan', 'key_number': 42 },
        { 'name': 'Республика Бурятия', 'url': 'resp-buryatiya', 'key_number': 43 },
        { 'name': 'Республика Дагестан', 'url': 'resp-dagestan', 'key_number': 44 },
        { 'name': 'Республика Карелия', 'url': 'resp-kareliya', 'key_number': 45 },
        { 'name': 'Республика Коми', 'url': 'resp-komi', 'key_number': 46 },
        { 'name': 'Республика Крым', 'url': 'crimea', 'key_number': 47 },
        { 'name': 'Республика Марий Эл', 'url': 'resp-mariy-el', 'key_number': 48 },
        { 'name': 'Республика Мордовия', 'url': 'resp-mordoviya', 'key_number': 49 },
        { 'name': 'Республика Якутия', 'url': 'resp-saha-(yakutiya)', 'key_number': 50 },
        { 'name': 'Республика Татарстан', 'url': 'resp-tatarstan', 'key_number': 51 },
        { 'name': 'Республика Хакасия', 'url': 'resp-hakasiya', 'key_number': 52 },
        { 'name': 'Ростовская область', 'url': 'rostovskaya-obl', 'key_number': 53 },
        { 'name': 'Рязанская область', 'url': 'ryazanskaya-obl', 'key_number': 54 },
        { 'name': 'Самарская область', 'url': 'samarskaya-obl', 'key_number': 55 },
        { 'name': 'Саратовская область', 'url': 'saratovskaya-obl', 'key_number': 56 },
        { 'name': 'Сахалинская область', 'url': 'sahalinskaya-obl', 'key_number': 57 },
        { 'name': 'Свердловская область', 'url': 'sverdlovskaya-obl', 'key_number': 58 },
        { 'name': 'Севастополь', 'url': 'sevastopol-r', 'key_number': 59 },
        { 'name': 'Смоленская область', 'url': 'smolenskaya-obl', 'key_number': 60 },
        { 'name': 'Ставропольский край', 'url': 'stavropolskiy-kray', 'key_number': 61 },
        { 'name': 'Тамбовская область', 'url': 'tambovskaya-obl', 'key_number': 62 },
        { 'name': 'Тверская область', 'url': 'tverskaya-obl', 'key_number': 63 },
        { 'name': 'Томская область', 'url': 'tomskaya-obl', 'key_number': 64 },
        { 'name': 'Тульская область', 'url': 'tulskaya-obl', 'key_number': 65 },
        { 'name': 'Тюменская область', 'url': 'tyumenskaya-obl', 'key_number': 66 },
        { 'name': 'Удмуртская область', 'url': 'udmurtskaya-resp', 'key_number': 67 },
        { 'name': 'Ульяновская область', 'url': 'ulyanovskaya-obl', 'key_number': 68 },
        { 'name': 'Хабаровский край', 'url': 'habarovskiy-kray', 'key_number': 69 },
        { 'name': 'Ханты Мансийск', 'url': 'hmao-yugra', 'key_number': 70 },
        { 'name': 'Челябинская область', 'url': 'chelyabinskaya-obl', 'key_number': 71 },
        { 'name': 'Ямало-Нененск', 'url': 'yanao', 'key_number': 72 },
        { 'name': 'Ярославская область', 'url': 'yaroslavskaya-obl', 'key_number': 73 },
        
    ],
    'categories': [
        {
            'name': 'Красота и здоровье',
            'url': 'krasota-i-zdorove',
            'key_number': 1
        }
    ],
}